name: crm_sales_performance_mobilis
description: "A CRM application for sales performance management with contact and prospect management."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.1.7
  flutter_phone_direct_caller: ^2.1.1
  table_calendar: ^3.0.0
  intl: ^0.19.0
  dio: ^5.8.0+1
  flutter_bloc: ^8.1.3
  sqflite: ^2.3.0
  path: ^1.8.3
  shared_preferences: ^2.2.2
  flutter_internet_speed_test: ^1.5.0
  flutter_contacts: ^1.1.9+2
  equatable: ^2.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
